# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ec3aNAx3gxaRce97inLDoxlYVr-AcQW6

# **Clone data from git**

**Load dữ liệu từ github ở link "https://github.com/NQT2906/CS114.K21" về và đặt tên là Dataset**
"""

!git clone "https://github.com/NQT2906/CS114.K21" Dataset

cd Dataset/Time

"""# **Import library**

**Import những thư viện cần thiết lúc đầu**
"""

import pandas as pd

"""# **Read data**

**Đọc dữ liệu với phương thức read_csv của thư viện pandas. 'data2.txt' là tên của file dữ liệu, sep = ',' là cho dữ liệu thêm 1 cột khi gặp dấu ','.
data.columns = ['Size', 'Time'] là đặt tên cho 2 cột dữ liệu vừa chia là Size và Time.**
"""

data = pd.read_csv('data2.txt', sep = ',', header = None)
data.columns = ['Size', 'Time']

X = data.iloc[:, 0].values.reshape(-1, 1)
Y = data.iloc[:, 1]

"""# **Split data to train and test**

**Chia bộ dữ liệu làm 2 phần là train và test nhờ vào phương thức train_test_split của thư viện sklearn với train_size = 80%**
"""

from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, train_size = 0.8, random_state = 0)

"""# **Choose model**

**Do input của bộ dữ liệu chỉ có 1 biến là Size nên ta dùng Linear Regression cho bộ dữ liệu này**
"""

from sklearn.linear_model import LinearRegression

lin_reg = LinearRegression()
lin_reg.fit(X_train, Y_train)

Y_train_pred = lin_reg.predict(X_train)
Y_test_pred = lin_reg.predict(X_test)

"""# **Visualize data and model**"""

import matplotlib.pyplot as plt

plt.scatter(X_train, Y_train, color = 'red')
plt.title('Size vs Time')
plt.xlabel('Size')
plt.ylabel('Time (s)')
plt.show()

plt.scatter(X_train, Y_train, color = 'red')
plt.plot(X_train, Y_train_pred, color = 'blue')
plt.title('Size vs Time')
plt.xlabel('Size')
plt.ylabel('Time (s)')
plt.show()

plt.scatter(X_test, Y_test, color = 'red')
plt.plot(X_train, Y_train_pred, color = 'blue')
plt.scatter(X_test, Y_test_pred, color = 'black')
plt.title('Size vs Time')
plt.xlabel('Size')
plt.ylabel('Time (s)')
plt.show()

"""# **Evaluate**"""

from sklearn.metrics import r2_score
print(r2_score(Y_train, Y_train_pred))
print(r2_score(Y_test, Y_test_pred))

